### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model

### ISSUE THREAD

**Issue by sebastianmuramara** [sebastianmuramara/134644-BIProject#6]
- [ ] Data Splitting
- [ ] Bootstrapping
- [ ] Cross Validation (Basic, Repeated or LOOCV)
- [ ] Model Training for either Classification, Regression, Association or Clustering (if applicable)
- [ ] Model Performance Comparison using Resamples (for classification and regression)
